apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: green
spec:
  config: '{
        "cniVersion":"0.3.1",
        "name":"green",
        "type":"ovn-k8s-cni-overlay",
        "ipam":{},
        "dns":{}
     }'
