---
apiVersion: v1
kind: Pod
metadata:
  name: on-green
  annotations:
   switches: '["green"]'
   k8s.v1.cni.cncf.io/networks: '[
            { "name": "green" }
    ]'
spec:
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  containers:
  - name: alpine
    image: alpine
    command:
    - sleep
    - "9999999999"
